# Classifying the MNIST Dataset using TensorFlow/Keras

Load TensorFlow

In [1]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.17.1


### Load the dataset

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


### Define the model

In [4]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.08469879, 0.06085797, 0.09217303, 0.03869495, 0.19645841,
        0.05248161, 0.12120848, 0.06879105, 0.14600128, 0.13863443]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.09837135, 0.09605383, 0.09910936, 0.0939484 , 0.11000317,
        0.09525261, 0.10202923, 0.09681886, 0.10459043, 0.10382276]],
      dtype=float32)

Define a loss function

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.351223

### Compile the model.
Using the above loss function, Adam optimizer, measuring accuracy

In [9]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

### Train and evaluate the model

In [10]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/nn.py:635: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8565 - loss: 0.4866
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9557 - loss: 0.1490
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9664 - loss: 0.1116
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9730 - loss: 0.0888
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9767 - loss: 0.0733
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9790 - loss: 0.0635
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9816 - loss: 0.0563
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9841 - loss: 0.0508
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9842 - loss: 0.0470
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9858 - loss: 0.0412


Check the model performance

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9801 - loss: 0.0700


[0.07003127783536911, 0.9800999760627747]

#### The overall model accuracy is 98%

### Creating a probability model

Wrap the previously trained model and attach a softmax

In [12]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533799, 0.08533799, 0.08533802, 0.08534627, 0.08533799,
        0.08533799, 0.08533799, 0.23194964, 0.08533803, 0.08533813],
       [0.08533733, 0.08534133, 0.23196   , 0.08533733, 0.08533733,
        0.08533733, 0.08533733, 0.08533733, 0.08533733, 0.08533733],
       [0.08534512, 0.23183674, 0.08535527, 0.08534526, 0.08534514,
        0.08534516, 0.0853455 , 0.08538632, 0.08535033, 0.08534512],
       [0.23196106, 0.08533727, 0.08533783, 0.08533727, 0.08533727,
        0.0853378 , 0.08533894, 0.08533742, 0.08533727, 0.0853379 ],
       [0.08536237, 0.08536236, 0.08536241, 0.08536236, 0.23156345,
        0.08536236, 0.08536237, 0.0853625 , 0.08536236, 0.08553743]],
      dtype=float32)>